### ISSUE TITLE
Building everything (Python 3, PyOtherSide and GPodder) from source

### ISSUE THREAD

**Issue by M4rtinK** [gpodder/gpodder-android#1]
So I've decided to find out how to get from the source code up to a working Android package & to put together a guide documenting how I did it. The guide follows (feel free to include it in a suitable place :) ):

Building GPodder as an example Python 3 + PyOtherSide + QtQuick 2.0 application
===============================================================================

Environment:
* Fedora 20
* Qt 5.3.1 Android SDK
* latest Android SDK with API level 14 installed
* OpenJDK 1.7
* a few GB of harddrive space
* and Android device connected to the computer

The build is going to be done in a folder called "build" in the users home directory,
lets say that the use is named "user" (replace accordingly for your environment).

We start in the home directory:

    mkdir build
    cd build

Now clone the needed projects, load submodules and switch to correct branches.

    git clone https://github.com/thp/python3-android
    git clone https://github.com/thp/pyotherside
    git clone https://github.com/gpodder/gpodder-android
    cd python3-android
    git checkout fixes
    cd ..
    cd gpodder-android
    git checkout fixes
    git submodule init
    git submodule update
    cd ..

Next we will build Python 3 for Android. This will first download the Android NDK, then Python 3 source code, followed by crosscompiling the Python 3 code for Android on ARM.

    cd python3-android
    make all

As the next step we modify the python.pri.android file to point to our Python build. If should look like this as a result (remember to modify it for your environment):

QMAKE_LIBS += -L/home/user/build/python3-android/build/9d-14-arm-linux-androideabi-4.8/lib -lpython3.3m -ldl -lm -lc -lssl -lcrypto
QMAKE_CXXFLAGS += -I/home/user/build/python3-android/build/9d-14-arm-linux-androideabi-4.8/include/python3.3m/

Then copy the file over the python.pri file in PyOtherSide:

    cd ..
    cp python3-android/python.pri.android pyotherside/python.pri

PyOtherSide can also help us ship & load the Python standard library if we can provide it a suitable zip bundle, which can be created like this:

    cd python3-android/build/9d-14-arm-linux-androideabi-4.8/lib/python3.3/
    zip -r pythonlib.zip *
    cd ../../../../..

For PyOtherSide to include the packed Python standard library it needs to be placed in its src subfolder:

    mv python3-android/build/9d-14-arm-linux-androideabi-4.8/lib/python3.3/pythonlib.zip pyotherside/src/

PyOtherSide will then use the qrc mechanism to compile the compressed standard library during inside it's own binary, removes the need for us to handle its shipping & loading ourself.

Now you will build PyOtherSide with QtCreator from the Qt 5.3 Android SDK, so make sure that the Qt 5.3 Android kit is using the exact same NDK that has been used to build Python 3 for Android. To do that go to settings, find kits, select the Android kit and make sure that the NDK path points to:

    /home/user/build/python3-android/sdk/android-ndk-r9d

Next open the pyotherside/pyotherside.pro project file on QtCreator, select the Android kit and once the project loads go to the project view and under "run" make sure that API level is set to 14 (Android 4.0 and later). The Android Python 3 build has been built for API level 14 and our PyOtherSide build should do the same to be compatible. 

Also make sure that shadow build is disabled (TODO: check if this is needed)

Once done with the configuration got to the "build" menu and select the "built pyotherside" options - this should build PyOtherSide for Android and statically
compile in our Python build and the Python standard library.

As the next step we need to move the PyOtherSide binary to the plugin folder for the Qt  Android SDK, so that it can be fetched by the SDK when building GPodder.

Let's say we have the SDK installed in the /data directory, giving us this path to the plugin folder:

    /data/Qt5.3/5.3/android_armv7/qml

So create the folder structure for the pyotherside plugin:

    mkdir -p /data/Qt5.3/5.3/android_armv7/qml/io/thp/pyotherside

And a corresponding qmldir file for the plugin:

    echo "module io.thp.pyotherside" > /data/Qt5.3/5.3/android_armv7/qml/io/thp/pyotherside/qmldir
    echo "plugin pyothersideplugin" >> /data/Qt5.3/5.3/android_armv7/qml/io/thp/pyotherside/qmldir

Then copy the pyotherside binary:

    cp build-pyotherside-Android_for_armeabi_v7a_GCC_4_8_Qt_5_3_2-Debug/src/libpyothersideplugin.so /data/Qt5.3/5.3/android_armv7/qml/io/thp/pyotherside/

(NOTE: The path to the build folder might be slightly different as it depending on Qt SDK version)

Next open the gpodder project in QtCreator (gpodder-android/gpodder-android.pro) and again make sure the Android kit is selected and the API level 14 is used. Then just press the "Run" button and the SDK should build an Android APK that includes the libpyotherside binary (as it is referenced in the GPodder QML source code) and deploy it to the device where GPodder should be started.

But unfortunately
=============

The resulting application crashes once deployed. :-P  
The application output before the crash looks like this:

**FIXED - WORKS NOW ** - see comment below for more info.

```
Starting remote process.D/dalvikvm(13794): Late-enabling CheckJNI
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libgnustl_shared.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libgnustl_shared.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libgnustl_shared.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Core.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Core.so 0x2b80ca18
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Network.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Network.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5Network.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Qml.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Qml.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5Qml.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Gui.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Gui.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5Gui.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Quick.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Quick.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5Quick.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5QuickParticles.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5QuickParticles.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5QuickParticles.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5Multimedia.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5Multimedia.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5Multimedia.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5MultimediaQuick_p.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libQt5MultimediaQuick_p.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libQt5MultimediaQuick_p.so 0x2b80ca18, skipping init
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/qt-reserved-files/plugins/platforms/android/libqtforandroid.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/qt-reserved-files/plugins/platforms/android/libqtforandroid.so 0x2b80ca18
I/Qt      (13794): qt start
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5QuickParticles.so 0x2b80ca18
D/dalvikvm(13794): Shared lib '/data/data/org.gpodder.android/lib/libQt5QuickParticles.so' already loaded in same CL 0x2b80ca18
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so 0x2b80ca18
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/qt-reserved-files/plugins/mediaservice/libqtmedia_android.so 0x2b80ca18
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libQt5MultimediaQuick_p.so 0x2b80ca18
D/dalvikvm(13794): Shared lib '/data/data/org.gpodder.android/lib/libQt5MultimediaQuick_p.so' already loaded in same CL 0x2b80ca18
D/dalvikvm(13794): Trying to load lib /data/data/org.gpodder.android/lib/libgpodder-android.so 0x2b80ca18
D/Qt      (13794): qml/qqmlengine.cpp:1453 (QQmlDebuggingEnabler::QQmlDebuggingEnabler(bool)): QML debugging is enabled. Only use this in a safe environment.
D/dalvikvm(13794): Added shared lib /data/data/org.gpodder.android/lib/libgpodder-android.so 0x2b80ca18
D/dalvikvm(13794): No JNI_OnLoad found in /data/data/org.gpodder.android/lib/libgpodder-android.so 0x2b80ca18, skipping init
D/libEGL  (13794): loaded /system/lib/egl/libGLES_android.so
D/libEGL  (13794): loaded /system/lib/egl/libEGL_adreno200.so
D/libEGL  (13794): loaded /system/lib/egl/libGLESv1_CM_adreno200.so
D/libEGL  (13794): loaded /system/lib/egl/libGLESv2_adreno200.so
D/OpenGLRenderer(13794): Enabling debug mode 0
F/libc    (13794): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1)


"org.gpodder.android" died.
```
Any pointer on what might be wrong ? Thanks in advance! :)

**Comment by thp** [comment]
Closing this as it seems to be working, and is documented in the PyOtherSide docs as well.
